# Generated by Django 3.2.7 on 2021-09-17 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandStat',
            fields=[
                ('epoch_time', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('command', models.CharField(max_length=2000)),
                ('invoked_with', models.CharField(max_length=2000)),
                ('invoked_subcommand', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('reminder_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(default='INVALID', max_length=2000)),
                ('author_id', models.CharField(default='INVALID', max_length=500)),
                ('author_name', models.CharField(default='INVALID', max_length=500)),
                ('message_id', models.CharField(default='INVALID', max_length=200)),
            ],
        ),
    ]
