# Generated by Django 3.2.7 on 2021-09-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandStat',
            fields=[
                ('epoch_time', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2021)),
                ('month', models.IntegerField(default=9)),
                ('day', models.IntegerField(default=20)),
                ('hour', models.IntegerField(default=18)),
                ('channel_name', models.CharField(default='NA', max_length=2000)),
                ('command', models.CharField(max_length=2000)),
                ('invoked_with', models.CharField(max_length=2000)),
                ('invoked_subcommand', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reminder_date_epoch', models.BigIntegerField(default=0)),
                ('message', models.CharField(default='INVALID', max_length=2000)),
                ('author_id', models.CharField(default='INVALID', max_length=500)),
                ('author_name', models.CharField(default='INVALID', max_length=500)),
                ('message_id', models.CharField(default='INVALID', max_length=200)),
            ],
        ),
    ]
