# Generated by Django 3.2.7 on 2021-09-28 22:41

import WalleModels.customFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalleModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUsers',
            fields=[
                ('username', models.CharField(max_length=32)),
                ('user_id', WalleModels.customFields.FixedCharField(max_length=18, primary_key=True,
                 serialize=False)),
            ],
            options={
                'db_table': 'WalleModels_banned_users',
            },
        ),
        migrations.CreateModel(
            name='BanRecords',
            fields=[
                ('ban_id', WalleModels.customFields.GeneratedIdentityField(always=True, primary_key=True,
                 serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('user_id', WalleModels.customFields.FixedCharField(max_length=18)),
                ('mod', models.CharField(max_length=32, null=True)),
                ('mod_id', WalleModels.customFields.FixedCharField(max_length=18, null=True)),
                ('date', models.DateTimeField(null=True, unique=True)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'WalleModels_ban_records',
                'unique_together': {('user_id', 'date')},
            },
        ),
    ]
