# Generated by Django 3.2.7 on 2021-09-28 22:41

import WalleModels.customFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalleModels', '0001_initial'),
    ]

    operations = [migrations.CreateModel(
            name='BanRecords',
            fields=[
                ('ban_id', WalleModels.customFields.GeneratedIdentityField(always=True, primary_key=True,
                 serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('user_id', models.BigIntegerField()),
                ('mod', models.CharField(max_length=32, null=True)),
                ('mod_id', models.BigIntegerField(null=True)),
                ('ban_date', models.BigIntegerField(null=True)),
                ('reason', models.TextField()),
                ('unban_date', models.BigIntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'WalleModels_ban_records'
            },
        ),
    ]
