# Generated by Django 3.2.7 on 2021-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalleModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
