# Generated by Django 3.2.7 on 2021-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalleModels', '0002_alter_reminder_reminder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_date_epoch',
            field=models.BigIntegerField(default=0),
        ),
    ]
