# Generated by Django 3.2.7 on 2021-09-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalleModels', '0003_auto_20210919_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandstat',
            name='channel_name',
            field=models.CharField(default='NA', max_length=2000),
        ),
        migrations.AddField(
            model_name='commandstat',
            name='day',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='commandstat',
            name='epoch_time',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commandstat',
            name='hour',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='commandstat',
            name='month',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='commandstat',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
