#!/bin/bash

postgresPassword=$POSTGRES_DB_PASSWORD
wallePassword=$WALl_E_DB_PASSWORD

postgresLine="ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD '${postgresPassword}';"
walleLine="ALTER ROLE wall_e WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '${wallePassword}';"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

sed -i '/ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD/c\'"$postgresLine" ${DIR}/database_config_file/backup.sql
sed -i '/ALTER ROLE wall_e WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD/c\'"$walleLine" ${DIR}/database_config_file/backup.sql