FROM python:3.5.5-alpine

ARG DOCKER_CONTAINER_TEST_RESULT_DIRECTORY

ARG UNIT_TEST_RESULTS

WORKDIR $DOCKER_CONTAINER_TEST_RESULT_DIRECTORY

COPY test-requirements.txt ./

COPY wall_e ./

COPY pytest.ini ./

COPY setup.cfg ./

RUN pip install --no-cache-dir -r test-requirements.txt

RUN mkdir -p mount/unit_results.xml

CMD ["sh" , "-c", py.test --junitxml=$UNIT_TEST_RESULTS" ]
