FROM python:3.5.5-alpine

WORKDIR /usr/src/app

COPY test-requirements.txt ./

COPY wall_e ./

COPY pytest.ini ./

COPY setup.cfg ./

RUN pip install --no-cache-dir -r test-requirements.txt

CMD py.test
