version: '3' #docker-compose version
services:  #Services that are needed for the wall_e app
    wall_e: #the wall_e app
        build: . #Saying that all of my source files are at the root path
        environment:
            - ENVIRONMENT
            - BOT_LOG_CHANNEL_ID
            - WOLFRAMAPI
            - TOKEN
            - COMPOSE_PROJECT_NAME
            - BRANCH
        volumes: #volume are for hot reload for exemple
            - "./app:/src/app"
            #- "${COMPOSE_PROJECT_NAME}_logs:/usr/src/app/logs"
        depends_on:   # used to ensure that docker wont start wall_e until after it has started the database container
            - "db"
        container_name: "${COMPOSE_PROJECT_NAME}_wall_e"
    db: #declaration of the postgres container
        image: postgres:alpine #using postgres image
        volumes: #used to pass the folder that contains the configuration for the database
            - ./database_config_file:/docker-entrypoint-initdb.d
        container_name: "${COMPOSE_PROJECT_NAME}_wall_e_db"