-- WALL_E_DB_USER - wall_e
-- WALL_E_DB_PASSWORD - wallEPassword
-- WALL_E_DB_DBNAME - csss_discord_db

CREATE USER :WALL_E_DB_USER WITH PASSWORD ':WALL_E_DB_PASSWORD';
CREATE DATABASE :WALL_E_DB_DBNAME;
GRANT CONNECT ON DATABASE :WALL_E_DB_DBNAME TO :WALL_E_DB_USER;
GRANT ALL PRIVILEGES ON DATABASE :WALL_E_DB_DBNAME TO :WALL_E_DB_USER;