FROM python:3.8.5-alpine

ARG CONTAINER_HOME_DIR

ENV CONTAINER_HOME_DIR=$CONTAINER_HOME_DIR

ARG UNIT_TEST_RESULTS

ENV UNIT_TEST_RESULTS=$UNIT_TEST_RESULTS

ARG TEST_RESULT_FILE_NAME

ENV TEST_RESULT_FILE_NAME=$TEST_RESULT_FILE_NAME



WORKDIR $CONTAINER_HOME_DIR

COPY CI/validate_and_deploy/1_validate/test_config_files/test-requirements.txt ./

COPY wall_e ./

COPY CI/validate_and_deploy/1_validate/test_config_files/pytest.ini ./

COPY CI/validate_and_deploy/1_validate/test_config_files/setup.cfg ./

RUN pip install --no-cache-dir -r test-requirements.txt

RUN mkdir -p $UNIT_TEST_RESULTS

CMD ["sh" , "-c", "py.test --junitxml=${UNIT_TEST_RESULTS}/${TEST_RESULT_FILE_NAME}" ]
