version: '3' #docker-compose version
services:  #Services that are needed for the wall_e app
    wall_e: #the wall_e app, the name will of the image will be ${COMPOSE_PROJECT_NAME}_wall_e
        build:
            context: ../../../ #Saying that all of my source files are at the root path
            dockerfile: CI/server_scripts/build_wall_e/Dockerfile.wall_e
            args:
              - ORIGIN_IMAGE
        environment:
            - basic_config__TOKEN
            - TOKEN
            - BOT_LOG_CHANNEL
            - BOT_GENERAL_CHANNEL
            - basic_config__BRANCH_NAME
            - basic_config__ENVIRONMENT
            - BRANCH_NAME
            - ENVIRONMENT
            - basic_config__COMPOSE_PROJECT_NAME
            - basic_config__WOLFRAM_API_TOKEN
            - COMPOSE_PROJECT_NAME
            - WOLFRAM_API_TOKEN
            - POSTGRES_DB_USER
            - POSTGRES_DB_DBNAME
            - POSTGRES_PASSWORD
            - database_config__WALL_E_DB_USER
            - database_config__WALL_E_DB_DBNAME
            - database_config__WALL_E_DB_PASSWORD
            - WALL_E_DB_USER
            - WALL_E_DB_DBNAME
            - WALL_E_DB_PASSWORD
            - basic_config__MEE6_AUTHORIZATION
            - MEE6_AUTHORIZATION
        depends_on:   # used to ensure that docker wont start wall_e until after it has started the database container
            - "db"
        container_name: "${COMPOSE_PROJECT_NAME}_wall_e"
    db: #declaration of the postgres container
        environment:
            - POSTGRES_PASSWORD
        image: postgres:alpine #using postgres image
        container_name: "${COMPOSE_PROJECT_NAME}_wall_e_db"
    wall_e_leveling_website:
        build:
            context: ../../../
            dockerfile: CI/server_scripts/build_wall_e/Dockerfile.website
        depends_on:
            - 'db'
        container_name: "${COMPOSE_PROJECT_NAME}_leveling_website"
        image: "${COMPOSE_PROJECT_NAME_lower}_leveling_website"
        ports:
            - "8081:8000"
        environment:
            - basic_config__TOKEN
            - database_config__WALL_E_DB_DBNAME
            - database_config__WALL_E_DB_USER
            - database_config__WALL_E_DB_PASSWORD
            - basic_config__COMPOSE_PROJECT_NAME
            - DB_PORT
            - HOST
        restart: unless-stopped
volumes:
    logs:
        external:
            name: "${COMPOSE_PROJECT_NAME}_logs"
