FROM python:3.9.13-alpine

EXPOSE 8000

WORKDIR /src

COPY wall_e_leveling_website/wall_e_leveling wall_e_leveling
COPY wall_e_leveling_website/wall_e_leveling_website wall_e_leveling_website
COPY wall_e_leveling_website/manage.py manage.py
COPY wall_e_leveling_website/requirements.txt requirements.txt
COPY wall_e_leveling_website/startup.sh startup.sh
COPY wall_e_leveling_website/wait-for-postgres.sh wait-for-postgres.sh
COPY wall_e/WalleModels WalleModels
COPY wall_e_leveling_website/wall_e_leveling_website/settings.py django_db_orm_settings.py

RUN apk add postgresql
CMD ["./wait-for-postgres.sh", "./startup.sh"]
#CMD ["sh"]
