FROM rocker/shiny:4.2.1
RUN rm -rf /srv/shiny-server/*
COPY web /srv/shiny-server/
RUN apt update && \
    apt -y install libpq5 python3-pip && \
    pip install pandas discord.py && \
    Rscript -e 'install.packages("RPostgres")' && \
    touch /srv/shiny-server/leaderboard/users.csv && \
    chown shiny:shiny /srv/shiny-server/leaderboard/users.csv && \
    cp /srv/shiny-server/leaderboard/shiny-customized.config /etc/shiny-server/shiny-server.conf
