node {
   stage('Cleanup PR') {
    withCredentials([string(credentialsId: 'TEST_BOT_USER_TOKEN', variable: 'TOKEN')]) {
      def object = readJSON text: "${payload}"
      def prNumber = object.number
      def branchName = object.pull_request.head.ref
      def dstBranchName = object.pull_request.base.ref
      def merged = object.pull_request.merged
      def action = object.action
      if (action == 'closed') {
          def resp = httpRequest customHeaders:
            [[maskValue: true, name: 'Authorization', value: "Bot ${TOKEN}"]],
            url: 'https://discordapp.com/api/users/@me/guilds'
          def guilds = resp.getContent()
          def guildObject = readJSON text: guilds
          def guildId = guildObject[0].id
          resp = httpRequest customHeaders:
            [[maskValue: true, name: 'Authorization', value: "Bot ${TOKEN}"]],
            url: "https://discordapp.com/api/guilds/${guildId}/channels"
          def channels = readJSON text: resp.getContent()
          def prChanId = channels.find{chan -> chan.name == "pr-${prNumber}"}.id
          def logChanId = channels.find{chan -> chan.name == "pr-${prNumber}_logs"}.id
          def reminderChanId = channels.find{chan -> chan.name == "pr-${prNumber}_reminders"}.id
          httpRequest customHeaders:
            [[maskValue: true, name: 'Authorization', value: "Bot ${TOKEN}"]],
            httpMode: 'DELETE', responseHandle: 'NONE',
            url: "https://discordapp.com/api/channels/${prChanId}"
          httpRequest customHeaders:
            [[maskValue: true, name: 'Authorization', value: "Bot ${TOKEN}"]],
            httpMode: 'DELETE', responseHandle: 'NONE',
            url: "https://discordapp.com/api/channels/${logChanId}"
          httpRequest customHeaders:
            [[maskValue: true, name: 'Authorization', value: "Bot ${TOKEN}"]],
            httpMode: 'DELETE', responseHandle: 'NONE',
            url: "https://discordapp.com/api/channels/${reminderChanId}"
          sh "docker rm -f TEST_PR-${prNumber}_wall_e TEST_PR-${prNumber}_wall_e_db"
          if (merged == false && dstBranchName == 'master') {
              sh "docker start TEST_${branchName}_wall_e TEST_${branchName}_wall_e_db"
          }
      }
      if ((action == 'opened' || action == 'reopened') && dstBranchName == 'master') {
          sh "docker kill TEST_${branchName}_wall_e TEST_${branchName}_wall_e_db"
      }
    }
   }
}
