FROM python:3.5.5-alpine

ARG CONTAINER_HOME_DIR

ENV CONTAINER_HOME_DIR=$CONTAINER_HOME_DIR

WORKDIR $CONTAINER_HOME_DIR

COPY wall_e/src/requirements.txt .

RUN apk add --update alpine-sdk libffi-dev && \
    apk add freetype-dev && \
    apk add postgresql-dev && \
    pip install -no-cache-dir Cython && \
    pip install --no-cache-dir -r requirements.txt &&  \
    apk --update add postgresql-client
