FROM python:3.5.5-alpine

ARG CONTAINER_HOME_DIR

ENV CONTAINER_HOME_DIR=$CONTAINER_HOME_DIR

ARG UNIT_TEST_RESULTS

ENV UNIT_TEST_RESULTS=$UNIT_TEST_RESULTS




WORKDIR $CONTAINER_HOME_DIR

COPY test-requirements.txt ./

COPY wall_e ./

COPY pytest.ini ./

COPY setup.cfg ./

RUN pip install --no-cache-dir -r test-requirements.txt

RUN mkdir -p $UNIT_TEST_RESULTS

CMD ["sh" , "-c", "py.test --junitxml=${UNIT_TEST_RESULTS}/all-unit-tests.xml" ]
